### ISSUE TITLE
Different performance scores on the same machine

### ISSUE THREAD

**Issue by pedrolgon** [sitespeedio/plugin-lighthouse#102]
Hi all
I executed sitespeed.io with the plugin lighthouse and I obtained different scores.
When I execute directly with node or I use docker, the score is much lower than I execute the lighthouse analyses with the Browser.

Chrome Browser scores

![image](https://user-images.githubusercontent.com/90193566/160168096-391b307c-7a7f-4872-acb3-1f696981ab6b.png)

Node or Docker

![image](https://user-images.githubusercontent.com/90193566/160168412-bb026241-40a7-4022-8c5f-8fcb9ca7e093.png)

I need a higher one for node and docker

This is the node execution

node node_modules/sitespeed.io/bin/sitespeed.js https://www.amazon.es/ --n 1 --browser chrome --plugins.add ../../../@sitespeed.io/plugin-lighthouse

Regards,

**Comment by soulgalore** [comment]
Hi @pedrolgon checkout https://github.com/GoogleChrome/lighthouse/issues/10657 for help. I think this is an issue with Lighthouse itself and gonna close the issue! 

Best
Peter

**Comment by pedrolgon** [comment]
Hi Peter,
Thanks so much
I read the issue but my problem is not the same
The score between different executions in node or docker is the same
but when I execute the lighthouse in the browser the score is always higher and this is a problem for us.
is this an usual behavior?
Regards,
Pedro

**Comment by StrangeWill** [comment]
We're experiencing the same issue with a score difference of 95/70, which is pretty drastic, will continue to dig on this.
