### ISSUE TITLE
Error in Package installation using NPM

### ISSUE THREAD

**Issue by shrutiseth** [sitespeedio/plugin-lighthouse#124]
I am getting error while installing this package using -  npm install sitespeed.io/plugin-lighthouse -g -y

[
![NPM Lighthouse Plugin error](https://github.com/siteriaitaliana/plugin-lighthouse/assets/45349166/fa1fa3d4-da2a-4d16-b6a9-3439d3f67e82)
](url)

Please help here!

**Comment by soulgalore** [comment]
Hi @shrutiseth you are missing  a @ in front of sitespeed.io, please try:
`npm install @sitespeed.io/plugin-lighthouse`

**Comment by shrutiseth** [comment]
Hi @soulgalore - Thanks for your response. But I get below error:

<img width="928" alt="image" src="https://github.com/sitespeedio/plugin-lighthouse/assets/45349166/b04688f9-05fe-4af9-aa4b-e2cbec3a20b4">

**Comment by shrutiseth** [comment]
I did - npm i @sitespeed.io/plugin-lighthouse
it did get installed. But when I ran audit using - 

<img width="944" alt="image" src="https://github.com/sitespeedio/plugin-lighthouse/assets/45349166/19849480-f3ab-4700-ada5-7ae3bf459df5">

it gives error - c_ode: 'ERR_MODULE_NOT_FOUND',
  _url: 'file:///C:/Users/shruti.s.seth/OneDrive%20-%20Accenture/PerfTools_SS/sitespeed.io/lib/plugin-lighthouse/index.js'__

It is not able to find lib/plugin-lighthouse/index.js, it is not there in directory either. 

So I downloaded from github and manually moved it to  /lib/ location, after which the audit ran.

Can you please check if the package is correct from your side? As last month it was all fine. Getting issue now only. I have to do the setup without docker, hence need your support. Thank you for your time!

**Comment by soulgalore** [comment]
I think on Windows the paths to the plugin maybe needs some love, I tried in a Windows GitHub action and it also fails for me. Installing globally works though, can you try that?

```
npm install sitespeed.io -g
npm install "@sitespeed.io/plugin-lighthouse" -g
sitespeed.io --plugins.add "@sitespeed.io/plugin-lighthouse" --plugins.remove browsertime https://www.sitespeed.io/
```

**Comment by shrutiseth** [comment]
@soulgalore  - Than you for your response. 
However when running the audit command, I am getting below:

<img width="960" alt="image" src="https://github.com/sitespeedio/plugin-lighthouse/assets/45349166/2f8d27eb-0819-4561-b289-6b17088bb6d7">

Nothing happens, and instead, "C:\Users\shruti.s.seth\AppData\Roaming\npm\sitespeed.io" file opens up as seen in my screenshot. I uninstalled nodejs, nvm, npm, deleted git repo and did everything again, still getting this error


Please advice!

Am trying to do whole setup without Docker. If you have a repo with Influx DB and Grafana integration, please do share the URL. Thanks.

**Comment by shrutiseth** [comment]
@soulgalore - Thank you so much for your quick response. It is working through Git Bash! :)

![image](https://github.com/sitespeedio/plugin-lighthouse/assets/45349166/351cd7cd-dd4b-4453-9cac-a28953a20736)

I have done InfluxDB setup, and created a database - sitespeed.

I used this command to send data to influxDB - _sitespeed.io https://www.sitespeed.io/ -n 1 -b chrome -influxdb.host 192.168.86.30 -influxdb.port 8086_

However, it results in this error:
<img width="478" alt="image" src="https://github.com/sitespeedio/plugin-lighthouse/assets/45349166/d96a994b-9e7b-4004-b89d-1415fb5599c1">

Can you please advise?

**Comment by shrutiseth** [comment]
Closing this issue as @soulgalore suggested to install Lighthouse package globally - 

_npm install sitespeed.io -g
npm install "@sitespeed.io/plugin-lighthouse" -g
sitespeed.io --plugins.add "@sitespeed.io/plugin-lighthouse" --plugins.remove browsertime https://www.sitespeed.io/_
