### ISSUE TITLE
screenshot in lighthouse viewport is still in desktop view

### ISSUE THREAD

**Issue by Aszzo** [sitespeedio/plugin-lighthouse#129]
I run lighthouse in the node.js runtime and always get desktop screenshots.
lighthouse configuration 
```
{
  disableStorageReset: true,
  logLevel: 'info',
  output: 'html',
  screenEmulation: {
    mobile: true,
    width: 360,
    height: 640,
    // Moto G4 is really 3, but a higher value here works against
    // our perf recommendations.
    // https://github.com/GoogleChrome/lighthouse/issues/10741#issuecomment-626903508
    deviceScaleFactor: 2.625,
    disabled: false,
  },
  emulatedUserAgent: MOTOG4_USERAGENT,
  formFactor: 'mobile',
  throttling: mobileRegular4G,
  onlyCategories: ['performance'],
  skipAudits: ['bf-cache'], // not working in headless mode
};
```
![image](https://github.com/sitespeedio/plugin-lighthouse/assets/22289676/12fad117-746e-48d0-945f-b375336e9a83)
![image](https://github.com/sitespeedio/plugin-lighthouse/assets/22289676/e6d6c770-3c49-493d-b188-4ffe5e417de4)

**Comment by soulgalore** [comment]
Hi @Aszzo I'm not sure I follow, is it that the viewport you set 360x640 becomes 412x823? Is that the up do take way to set things in Lighthouse, I haven't tested how it works nowadays.

**Comment by Aszzo** [comment]
@soulgalore 
the viewport i set 360x640, but the screenshots in the ligthouse report is not mobile screenshots. maybe deskstop screenshots
![image](https://github.com/sitespeedio/plugin-lighthouse/assets/22289676/59dd926c-440e-4511-8b6e-932ba17938a9)
My code probably looks like this

**Comment by Aszzo** [comment]
@soulgalore Sorry bro, I was dazzled and thought this was a lighthouse repro. I'll close this issue
