### ISSUE TITLE
Add precommit hook for linting/line ending normalization?

### ISSUE THREAD

**Issue by gidztech** [sitespeedio/plugin-lighthouse#15]
Normally, my config for VS Code is to format on save. However, it wasn't working when I committed some changes in this project.  It turned out  `"editor.formatOnSave": true` was enough and I needed to also add the following to my editor settings:

```json
"[javascript]": {
    "editor.formatOnSave": true
}
```

CI failed because of prettier errors, but I think we shouldn't even get to CI if there are linting errors. Not everyone has formatting on save set up (or didn't work in my case). 

A precommit hook for linting could catch and fix the fixable errors as files get staged, and stop the commit in other cases.

We might also want `.gitattributes` and `.editorconfig` for line ending normalization.

I think this would be needed for all the SitespeedIO repositories?

**Comment by soulgalore** [comment]
Hi @gidztech you are right there are some things we can fix, let us sync that next week!

Best
Peter
