### ISSUE TITLE
Add --ignore-certificate-errors to default chromeFlags

### ISSUE THREAD

**Issue by djusv** [sitespeedio/plugin-lighthouse#3]
While trying to run against servers with self signed certificates I noticed that the lighthouse didn't return any values. Adding --ignore-certificate-errors to the default chrome flags worked for me.

**Comment by gidztech** [comment]
I've just run into this problem myself while running Lighthouse against our app running on a local environment. I'm going to work on this and raise a PR.

**Comment by soulgalore** [comment]
Merged this going out in next release.

**Comment by gidztech** [comment]
I actually looked into this in the afternoon and evening and don't have a working solution. 

The `--ignore-certificate-errors` flag that you added will not fix this problem as it doesn't alter the way Devtool Protocol clients, like Lighthouse, see the security state of the website. 

I believe it can be done low level by setting `Security.setOverrideCertificateErrors({ override: true });` but only from within the Lighthouse client, not as a Chrome flag. That's my understanding.

See https://github.com/GoogleChrome/lighthouse/issues/7292 and https://github.com/GoogleChrome/lighthouse/issues/6655 for more detail.

**Comment by soulgalore** [comment]
Ok thanks for looking into it.

**Comment by gidztech** [comment]
I raised a PR in the main repository for being able to pass in an additional start script that can import certificates into the container's certificate store as a workaround here.

**Comment by soulgalore** [comment]
Cool I guess this is fixed then.
