### ISSUE TITLE
Basic Auth headers

### ISSUE THREAD

**Issue by ilikerobots** [sitespeedio/plugin-lighthouse#30]
Do you know any way to the lighthouse plugin to pass basic auth headers?  I've tried every combination I can think of, e.g.

```
--lighthouse.settings.extra-headers '{"Authorization":"Basic <<base65token>>"}'
--lighthouse.settings.extraHeaders '{"Authorization":"Basic <<base65token>>"}'
--lighthouse.extraHeaders '{"Authorization":"Basic <<base65token>>"}'
```
etc

Some apparently have effect, but I get this message from Sitespeed:
```
Lighthouse got the following errors: {"protocolMethod":"Network.setExtraHTTPHeaders","protocolError":"Invalid parameters"} (lighthouse)
```

**Comment by soulgalore** [comment]
Hi @ilikerobots I had go like this:
`... https://httpbin.org/basic-auth/test/test -n 1 --lighthouse.settings.extra-headers {"Authorization":"Basic CdGVzDdDp0ZXN0"}`

but get:
(Network.setExtraHTTPHeaders): Invalid parameters (headers: object expected)

I tried also tried a hack where I JSON.parsed just that setting and set it to Lighthouse but got the same. Can you verify that it works if you run Lighthouse standalone?

Best
Peter

**Comment by ilikerobots** [comment]
@soulgalore 

Yes, it looks like lighthouse works ok with extra-headers when run with:
```
lighthouse --chrome-flags="--headless --disable-gpu" --extra-headers '{"Authorization": "Basic dGVzdDp0ZXN0"}'  https://httpbin.org/basic-auth/test/test
```

**Comment by soulgalore** [comment]
Ok, thanks. Wonder then if we do something wrong or if it's broken when you run Lighthouse direct from node? Thinking maybe something in the API is the problem.

**Comment by alexparish** [comment]
Don't suppose either of you found a solution to this?

**Comment by robinjoh90** [comment]
Any news here? Http auth can be set in the URL instead (not a optimal solution) but I also want to use --lighthouse.settings.extra-headers to set a cookie. I get the same error when I try to o that. 
(Network.setExtraHTTPHeaders): Invalid parameters (headers: object expected)

I've also tried putting the headers in a external file with option --lighthouse.settings.extra-headers=./headers.json but I get the same error.

**Comment by robinjoh90** [comment]
I think I have found the issue (and a workaround).  I used the --verbose flag on the sitespeed.io command and found out that when you pass the json-options in the parameter `--lighthouse.settings.extra-headers {"Authorization":"Basic << base65token>>"}` as @soulgalore suggested the extra-headers become a string in the json configuration.  

Like this 
```
"lighthouse": {
      "settings": {
        "extra-headers": "{\"Authorization\":\"Basic << base65token>>\",\"Cookie\": \"happy=true\"}",
        "extraHeaders": "{\"Authorization\":\"Basic << base65token>>\",\"Cookie\": \"happy=true\"}"
      }
    }
```

But you can can work around this by passing a json-config to sitespeed.io and it will work
**config.json**
```
{
  "lighthouse": {
      "settings": {
        "extra-headers": {"Cookie": "happy=true", "Authorization":"Basic << base65token>>"},
        "extraHeaders": {"Cookie": "happy=true", "Authorization":"Basic << base65token>>"}
      }
    }
}
```
Then run
`sudo docker run --shm-size=1g --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io:11.9.3-plus1 --config config.json http://www.domain.com/`

**Comment by ilikerobots** [comment]
I can confirm the method @robinjoh90 describes works.  Thanks a ton, @robinjoh90 .

**Comment by alexparish** [comment]
FWIW, I managed to pass a Cookie using the following argument:

`--lighthouse.settings.extraHeaders.Cookie cookieName=cookieValue`

I assume a similar approach could also work for passing the Authorization HTTP header.
