### ISSUE TITLE
How can we send lighthouse emulated form factor value to graphite

### ISSUE THREAD

**Issue by aprak7** [sitespeedio/plugin-lighthouse#34]
When running the lighthouse command from sitespeed, how do we send the emulated form factor data to graphite? So, that I can differentiate between the mobile and desktop scores in Grafana dashboard.

**Comment by soulgalore** [comment]
Hi @aprak7 is that per run or does lighthouse test the same within the run? If is different runs, you can use --graphite.namespace to set different namespaces. Is it within the run, you should be able to configure it through configuration, checkout https://github.com/sitespeedio/plugin-lighthouse#data-to-graphiteinfluxdb

Best
Peter

**Comment by Naverin89** [comment]
@aprak7 Hi, I've managed to add tag (I use InfluxDB) in the script. --influxdb.tags "form=desktop". Think something like this exists for Graphite also.

**Comment by aprak7** [comment]
Thanks! I have used --graphite.namepsace and it worked.
