### ISSUE TITLE
[Feature request] Lighthouse iterations

### ISSUE THREAD

**Issue by tengremlin** [sitespeedio/plugin-lighthouse#35]
Hi,
We've spoke briefly about this on Slack and I'm raising this here as suggested to bring it in front of broader audience.

It would help a lot if this plugin would enable possibility to define how many times it should run audits in similar manner as Browsertime does. This is necessary in order to deal with the variability of the results as described [here](https://github.com/GoogleChrome/lighthouse/blob/master/docs/variability.md) and [here](https://www.sitespeed.io/documentation/sitespeed.io/best-practice/#how-many-runs-should-i-do-on-the-same-page-to-get-stable-metrics) especially when collecting additional (timing) metrics beside the default ones.

To better visualise what I'm talking about let me show some example results from mine test runs:
<img width="1570" alt="Screenshot 2019-09-30 at 16 26 00" src="https://user-images.githubusercontent.com/15988668/65888138-519c1700-e39f-11e9-9c9e-dbd642a06db9.png">
Each run was performed on the same version of the application.

That being said, I've already made some work towards adding such feature. I still need to test it though and modify report generation for Lighthouse since right now result from just single run is generated. Once I'll polish it a little bit I will happily share it with you.

However, there is one issue that I don't know how should I proceed with. Since the output data would be different it should be considered as major change. Let me give you an example. Previously for the speed-index I had such results:
```
"speed-index": {
         [...some not relevant descriptive keys]
          "numericValue": 3544.8719908793323,
        }
```
so I would query in Grafana for `[some other keys along the line].lighthouse.audits.speed-index.numericValue`.

I've used `statHelpers` to aggregate results from multiple iterations, so now after calling `summarizeStats` I've got this as result:
```
"speed-index": {
      "median": 2336,
      "mean": 2336,
      "min": 2331,
      "p90": 2340,
      "max": 2340
    }
```
That query `[some other keys along the line].lighthouse.audits.speed-index.numericValue` will no longer return any results, and display empty dashboards for users that were collecting those metrics.

I came up with couple solutions but none of them is flawless:
- Release new major version of sitespeed - but not sure whether this plugin should influence versioning of sitespeed
- Release the change under `-plus2` image - if it would mean discontinuing `plus1` that might be the best way, otherwise it might add some troublesome maintenance, but even then I'm not sure whether this plugin should be released/versioned this way from now on forward
- Add switch to the code depending on how many times LH was running (if one, preserve old raports/data structure) - but it adds unnecessary complexity to code that could be avoided
- leave old keys as value of first/last/average run - it seems hacky and counterintuitive for somebody who would get to use it for the first time/didn't know the reason behind it

**Comment by soulgalore** [comment]
Hi @tengremlin so historically I've always been little sceptical to the timing metrics in Lighthouse,
since there hasn't been any good throttling and the limitations of creating visual metrics from the tracelog (there's a max number of images that can be stored). 

I'm thinking that the switch could be the best? Since if you run Lighthouse by default, most timing (all?) are guesstimates using Lantern so then multiple runs wouldn't matter or how does that actually works? My thinking (not saying that I'm right though, please tell me if I'm wrong) is that Lighthouse is good for getting an overall feeling and tips to get your page faster, and Browsertime/WebPageTest is more for getting stable metrics for monitoring.

Best
Peter

**Comment by tengremlin** [comment]
I don't know how LH timings are being computed to be honest, but results vary between the runs, so being able to discard edge results by taking median for example should improve determinism.

I would be happy to use Browsertime instead, but LH results was chosen as company standard in my workplace, so I just wanted to improve it at least.

And I'm ok with adding switch. I'll submit PR once I have something worth reviewing.

**Comment by tengremlin** [comment]
Hi @soulgalore 
So I finally was able to implement this feature and I hope it's good enough to be approved. Let me know if you have any suggestions regarding the changes.
Cheers

**Comment by soulgalore** [comment]
Hi @tengremlin cool, I'll have a go and test it later this week (by the weekend at the latest).
Best
Peter
