### ISSUE TITLE
Unable to view lighthouse data by connection dimension

### ISSUE THREAD

**Issue by andyfuh** [sitespeedio/plugin-lighthouse#37]
When running lighthouse tests as part of a test run, and shaping the connection to simulate 3g, 4g or wifi for example, you are unable to create a dashboard that filters using that dimension.

The detailed HTML reports contain the correct results for each run but you are unable to plot any results in a dashboard.

I am including the following custom metrics, which are visible in the graphite data.
	"metrics": {
		"filter": [
			"lighthouse.pageSummary.audits.first-contentful-paint.numericValue",
			"lighthouse.pageSummary.audits.first-meaningful-paint.numericValue",
			"lighthouse.pageSummary.audits.speed-index.numericValue",
			"lighthouse.pageSummary.audits.first-cpu-idle.numericValue",
			"lighthouse.pageSummary.audits.interactive.numericValue"
		]
	}

Is there a way by which the data can be aggregated by connection?

**Comment by soulgalore** [comment]
I think that the original issue been solved.
