### ISSUE TITLE
headless mode causes extreme variations in lighthouse, allow override

### ISSUE THREAD

**Issue by rdsubhas** [sitespeedio/plugin-lighthouse#38]
### Without `headless` mode

```
lighthouse --view "https://www.omio.com.br"
```
<img width="742" alt="image" src="https://user-images.githubusercontent.com/1570745/69495799-3d6e2500-0ecb-11ea-9114-37ff7d3af2db.png">

### With `headless` mode

```
lighthouse --view --chrome-flags="--headless" "https://www.omio.com.br"
```

<img width="738" alt="image" src="https://user-images.githubusercontent.com/1570745/69495803-4ced6e00-0ecb-11ea-9afe-db978e08a32a.png">

### Suggestion

* Though this is an upstream lighthouse bug, it would still be great to have a small fix in `plugin-lighthouse` by just removing `headless` mode for puppeteer in `runAudit.js`: https://github.com/sitespeedio/plugin-lighthouse/blob/master/runAudit.js#L6

**Comment by rdsubhas** [comment]
Issue raised in lighthouse: https://github.com/GoogleChrome/lighthouse/issues/10014

**Comment by soulgalore** [comment]
Yeah this is something I've preaching since day one but it seems like the Chrome team has a bigger church than me :D I think this is why should use tools like sitespeed.io (or WebPageTest if you prefer that) to measure the performance.

Thanks for the PR! I'll have a look asap!
