### ISSUE TITLE
Error: Lighthouse score is null and LCP returns NO_LCP

### ISSUE THREAD

**Issue by jameslk** [sitespeedio/plugin-lighthouse#53]
The latest version of this plugin [seems to be using Lighthouse v6](https://github.com/sitespeedio/plugin-lighthouse/blob/755e5d2bfc3a50d597b888c18ec64c2f27226b1b/package.json#L44), however the Lighthouse score and LCP metric have an error:

![Screen Shot 2020-05-24 at 5 36 22 PM](https://user-images.githubusercontent.com/774411/82767479-1eead700-9de5-11ea-87aa-b690f018e581.png)

I looked up the error and found this issue:
https://github.com/GoogleChrome/lighthouse/issues/10499

Based on the information in this issue, the error is likely caused by using an older version of Chromium that doesn't support the LCP metric. From my understanding, ideally this [should be Chromium v83](https://chromium.googlesource.com/chromium/src/+/master/docs/speed/metrics_changelog/lcp.md).

Looking at the dependency used for the browser, I see its [driven by an old version of Puppeteer (v1.19.0)](https://github.com/sitespeedio/plugin-lighthouse/blob/755e5d2bfc3a50d597b888c18ec64c2f27226b1b/package.json#L46). This version is [using Chromium v77](https://github.com/puppeteer/puppeteer/releases/tag/v1.19.0). The latest version of Puppeteer (v3.1.0) [uses Chromium v83](https://github.com/puppeteer/puppeteer/releases/tag/v3.1.0).

**Comment by soulgalore** [comment]
Hi @jameslk thanks you are right! I thought Lighthouse picked the version from it owns peer dependencies but that was wring. I just updated the dependency.

**Comment by jameslk** [comment]
Thank you for the fast release! I just updated to your latest commit and it looks like the error is gone 🍻
