### ISSUE TITLE
Metrics for multiple urls are mixed together, giving incorrect summaries

### ISSUE THREAD

**Issue by andrewmee** [sitespeedio/plugin-lighthouse#54]
I'm running sitespeed with the lighthouse plugin and using a targets.txt file with two urls, and I noticed that the reports created for the second url don't appear to be correct (there's always way too wide a variance between the fastest and slowest run).  

That led me to add some debugging into the plugin so I could see the metrics that are returned in each iteration.

```
Iterations:
      "largestContentfulPaint": 2743,
      "largestContentfulPaint": 1908,
      "largestContentfulPaint": 1940,
      "largestContentfulPaint": 5075,
      "largestContentfulPaint": 1908,

Summary:
      "largest-contentful-paint": {
          "median": 1939.64,
          "mean": 2714.94,
          "min": 1908.17,
          "p90": 5075.21,
          "max": 5075.21
        },

Iterations (url 2):
      "largestContentfulPaint": 7876,
      "largestContentfulPaint": 8335,
      "largestContentfulPaint": 8222,
      "largestContentfulPaint": 8213,
      "largestContentfulPaint": 8836,

Summary (url 2):
      "largest-contentful-paint": {
        "median": 6475.79,
        "mean": 5505.73,
        "min": 1908.17,
        "p90": 8836.26,
        "max": 8836.26
      },
```

As you can see the summary for the first results is correct, but the summary for the second results doesn't bare much of a resemblance to the iterations it's meant to be summarising.  The minimum value appears to be copied from the first url's minimum, and the median and mean are figures that don't appear anywhere.

**Comment by soulgalore** [comment]
Aha ok. Here's the original implementation https://github.com/sitespeedio/plugin-lighthouse/pull/36 - I haven't touched that part myself, any chance you could have a look? My guess it that the implementation than only handles one URL per run.

**Comment by andrewmee** [comment]
Yeah no problem - looking into it now, and I'll raise an PR if I can fix it :)

**Comment by andrewmee** [comment]
Issue fixed in https://github.com/sitespeedio/plugin-lighthouse/commit/fe5dec9a6e4caa6501a46e336e4522c5be99c903
