### ISSUE TITLE
Report numeric value alongside binary score where available

### ISSUE THREAD

**Issue by andrewmee** [sitespeedio/plugin-lighthouse#56]
Lighthouse reports the Time To First Byte ("server-response-time" audit) as a binary score - either 0 or 1 for pass or fail.  It also however logs the numeric value that was measured which is really useful to display in grafana dashboards.

Unfortunately at the moment those numeric values aren't included in the aggregator so they're not available to grafana.

Would you consider including it as a separate value?

Please see below where I've added a new code block to the existing addToAggregate function https://github.com/sitespeedio/plugin-lighthouse/blob/main/aggregator.js#L21

```js
  addToAggregate(result) {
    forEach(result.categories, category => {
      this._pushStats(['categories', category.id], category.score);
    });

    forEach(result.audits, audit => {
      this.log.info('Audit info', audit.id, audit.scoreDisplayMode);
      switch (audit.scoreDisplayMode) {
        case 'numeric':
          this._pushStats(['audits', audit.id], audit.numericValue);
          break;
        case 'binary':
          this._pushStats(['audits', audit.id], audit.score);
          // We could push the numeric value into a new reported stat to make it available alongside the existing score
          if (audit.numericValue) {
            this._pushStats(
              ['audits', audit.id + '-value'],
              audit.numericValue
            );
          }
          break;
        default:
          break;
      }
    });
  }
```

**Comment by soulgalore** [comment]
For Google Web Vitals I added so we report both, I think that is ok for now.
