### ISSUE TITLE
Options to pass in?

### ISSUE THREAD

**Issue by brentrobbins** [sitespeedio/plugin-lighthouse#6]
Are there any options to remove the audit reports for things like PWA and SEO if we would like to not include those in the report?

Also how do you tell it what device to use (desktop or mobile)?

Thanks for your help and super helpful plugin!

**Comment by soulgalore** [comment]
Hi @brentrobbins by default it runs everything by default. But everything you pass on --lighthouse.* will be passed on to lighthouse as options, so it should be possible to configure it how you want it. But let me know how it works, I haven't tried it myself :)

> Are there any options to remove the audit reports for things like PWA and SEO if we would like to not include those in the report?

You mean in the HTML, or data sent to Graphite/InfluxDB? No way in the HTML, the others are configurable.

Best
Peter

**Comment by MaximSergeichik** [comment]
Hi @soulgalore 

I've passed desktop parameter with following flag `--lighthouse.emulated-form-factor desktop \` into sitespeed but in lighthouse log I still see that lighthouse emulates mobile device.
More details you can find in attached log.

[sitespeed.log](https://github.com/sitespeedio/plugin-lighthouse/files/2899921/sitespeed.log)

Looking forward to you answer,

Best Regards,
Maksim

**Comment by soulgalore** [comment]
I’m on vacation this week and can have a look later this week, if you have time check if you can debug it yourself. Is there something wrong with how we pass on the config?

Best
Peter

**Comment by soulgalore** [comment]
Yeah this seems broken, we don't even pass them on the right way. If someone could help out with this it would be great.

**Comment by gidztech** [comment]
I've made a PR that should fix the issue. We were passing the Lighthouse config into the wrong parameter of the API. See https://github.com/sitespeedio/plugin-lighthouse/pull/10 for details.

It should be possiblee to set the device type using the following if/once merged:

`--lighthouse.extends lighthouse:default --lighthouse.settings.emulatedFormFactor desktop`

**Comment by soulgalore** [comment]
Fixed by @gidztech , I'll release the container tonight.
