### ISSUE TITLE
Update to latest lighthouse 6.3.0 dependency

### ISSUE THREAD

**Issue by johanblomgren** [sitespeedio/plugin-lighthouse#60]
Hi! First of all, thank you for this awesome plugin 👍 

Are there any known issues preventing an upgrade to `lighthouse` 6.3.0, which is the latest release on `npm.org`?
We're seeing discrepancies between for example CLS measurements between Lighthouse 6.1.0 and 6.3.0.

Thanks in advance!

**Comment by soulgalore** [comment]
Hej Johan, thanks for the kind words. Not that I know about, it's more that I haven't followed new releases on Lighthouse. I'll update the dependencies so we run the latest. If you use the Docker container, I'm gonna release that on Sunday/Monday.

**Comment by soulgalore** [comment]
https://github.com/sitespeedio/plugin-lighthouse/pull/61 - I updated to latest LH and Chrome in that PR.

**Comment by johanblomgren** [comment]
Hi! Awesome - much appreciated!
Looking forward to the release 👍

Do you know if the new release will be picked up by the sitespeed.io plus1 image build automatically or should one notify the maintainers about the new version?

Thanks!

**Comment by soulgalore** [comment]
It will be picked up automatically since I maintain it :)

**Comment by johanblomgren** [comment]
I can verify that we're getting the latest version of `lighthouse` as of writing using the sitespeed.io 1.5.0-plus1 image.
Thanks for the swift response!
