### ISSUE TITLE
Can't run Lighthouse tests on pages behind auth

### ISSUE THREAD

**Issue by fabis94** [sitespeedio/plugin-lighthouse#64]
I'm running the latest version of the plus1 Docker container: sitespeedio/sitespeed.io:15.6.4-plus1
And the command looks something like this:

```
docker run --cap-add=NET_ADMIN  --shm-size=2g --rm -v "$(pwd)/config":/config -v "$(pwd)":/sitespeed.io -v /etc/localtime:/etc/localtime:ro -e MAX_OLD_SPACE_SIZE=4096 sitespeedio/sitespeed.io:15.6.4-plus1 --graphite.namespace sitespeed_io.desktopPrivateUrls --config /sitespeed.io/config/desktop.json -b chrome --preScript /sitespeed.io/lib/login.js https://www.example.com/logged-in/dashboard
```

I was trying to use a preScript to log in first, and this works for Browsertime, but apparently Lighthouse starts a new Chrome session and it doesn't look like scripts can be used in any way there. Thus I can't log in to prepare the session for testing before running Lighthouse tests there.

Lighthouse does have an npm package, so maybe it can be ran from sitespeed.io scripts directly?

**Comment by soulgalore** [comment]
Hi @fabis94 Browsertime and Lighthouse uses different sessions, so using a preScript will not work. There's a way to run Puppeteer before Lighthouse run that a user contributed but there's no documentation. Checkout https://github.com/sitespeedio/plugin-lighthouse/pull/17

**Comment by fabis94** [comment]
Thanks, managed to get it working. For anyone else who finds this, you have to write a custom preScript that accepts 'browser' as its only parameter, and 'browser' is an instance Puppeteer's Browser. Using this instance you have to create a new page, log in to your site (or whatever) and then return without destroying the new page.

To make sure Lighthouse uses this script you need to use the `--lighthouse.preScript` CLI argument.

For me, the final command ended up looking like this:
```
docker run --cap-add=NET_ADMIN  --shm-size=2g --rm -v "$(pwd)/config":/config -v "$(pwd)":/sitespeed.io -v /etc/localtime:/etc/localtime:ro -e MAX_OLD_SPACE_SIZE=4096 sitespeedio/sitespeed.io:15.6.4-plus1 --graphite.namespace sitespeed_io.desktopPrivateUrls --config /sitespeed.io/config/desktop.json -b chrome --preScript /sitespeed.io/lib/login.js  --lighthouse.preScript /sitespeed.io/lib/loginPuppeteer.js https://example.com/behind-auth/portal
```

As you can see, both the Browsertime login preScript and the Lighthouse login preScript are necessary.
