### ISSUE TITLE
Update lighthouse version to latest(v7.2.0)

### ISSUE THREAD

**Issue by soobing** [sitespeedio/plugin-lighthouse#71]
Lighthouse [NEW VERSION](https://github.com/GoogleChrome/lighthouse/releases/tag/v7.2.0) released.

I had [PROTOCOL_TIMEOUT](https://github.com/GoogleChrome/lighthouse/issues/6512) error in `sitespeed plugin-lighthouse` and `lighthouse cli` both.
But after update lighthouse cli to v7.2.0, still got error but not fail the test.

So I ask you to update the version of sitespeedio/plugin-lighthouse to latest.

**Comment by soulgalore** [comment]
I've made a PR, please feel free to do one yourself the next time :)
