### ISSUE TITLE
Lighthouse report unavailable after run

### ISSUE THREAD

**Issue by andyfrancis** [sitespeedio/plugin-lighthouse#74]
Hi,

After a performance test completes, we have Sitespeed configured to push the results to an S3 bucket for long-term storage.  When viewing the report, we have the lighthouse option however the report URL is unavailable (404) - having looked at the s3 bucket directly it appears that there is no report in the /data directory.

Steps to reproduce:

1. with the sitespeed.io:16.9.2-plus1 docker image
2. Run the test and view results of the run on the published URL via S3 bucket
3. Within the report select a specific page and select the lighthouse option
4. Note the 404 error in the frame

Looking in the S3 bucket it appears the test has not been run for the specific page requested, but for the domain and I can see the lighthouse.1.html file in: [domain]/[date]/pages/[domain]/data/lighthouse.1.html

**Comment by soulgalore** [comment]
Hi @andyfrancis I don't think it should be something special with uploading that should break it. Do you use an alias for your URL? If so this https://github.com/sitespeedio/plugin-lighthouse/issues/72 is the problem, I'll fix that in the couple of days.

If you do not use an alias, please share how your run your tests so I can reproduce.

Thanks!

**Comment by andyfrancis** [comment]
Hi,

Yes we do use an alias on the bucket so that would make sense :).  I'll try again after the fix and let you know.

**Comment by EdBoyd** [comment]
Hi @andyfrancis I've just tried 16.10.0  v7 lighthouse now and this working for me - worth a try following https://github.com/sitespeedio/sitespeed.io/releases/tag/v16.10.0

**Comment by soulgalore** [comment]
Yep the alias fix is there now.
