### ISSUE TITLE
Lighthouse error when running a GPSI test with the Plus1 container

### ISSUE THREAD

**Issue by shaqb** [sitespeedio/plugin-lighthouse#77]
When running the following command:

_docker run --rm -v "$(pwd):/sitespeed.io" sitespeedio/sitespeed.io:16.10.0-plus1 "https://www.zoopla.co.uk/for-sale/property/london/" --browsertime.iterations 1 --plugins.remove /lighthouse_

I get a successful Sitespeed.io report but I get the following error in the console:

```
ERROR: Error: Lighthouse returned error: Something went wrong.
    at Gaxios.<anonymous> (/gpsi/node_modules/gaxios/build/src/gaxios.js:72:27)
    at Generator.next (<anonymous>)
    at fulfilled (/gpsi/node_modules/gaxios/build/src/gaxios.js:16:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

And subsequently I don't get any GPSI data as part of the run (we're looking to collect Lighthouse scores for long term trending)

I thought it might be a connectivity issue, but if I run the following test:

 _docker run --rm -v "$(pwd):/sitespeed.io" sitespeedio/sitespeed.io:16.10.0-plus1 "https://www.zoopla.co.uk/" --browsertime.iterations 1 --plugins.remove /lighthouse_

I get no issues at all. I get the following message: 

`INFO: Got https://www.zoopla.co.uk/ analysed from Google Page Speed Insights`

I have also tried running https://www.zoopla.co.uk/for-sale/property/london/ on GPSI directly and it works fine: (https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fwww.zoopla.co.uk%2Fto-rent%2Fproperty%2Flondon%2F&tab=mobile).

**Comment by soulgalore** [comment]
HI @shaqb thanks for creating the issue, let me try and see if I understand what's going on.

**Comment by shaqb** [comment]
Hi @soulgalore - thanks for the reply. That's really interesting as every time I hit GPSI directly it works fine.

![image](https://user-images.githubusercontent.com/19668009/111287550-3e384680-863b-11eb-9b1a-5b8d48d8a82f.png)

I even used the Pagespeed API and that also returned data correctly.

**Comment by shaqb** [comment]
Hi @soulgalore - are you able to still recreate the issue on GPSI directly as I am unable to. If you are are you able to share any more output so I can raise it?

**Comment by soulgalore** [comment]
I tried twice just now, first time it didn't work, the next time it did. When It didn't work, the only errors showed was the one in the screenshot.

**Comment by shaqb** [comment]
Thanks @soulgalore - I'll pass that on
