### ISSUE TITLE
When running a sitespeed.io with Lighthouse I get LHError: PROTOCOL_TIMEOUT

### ISSUE THREAD

**Issue by shaqb** [sitespeedio/plugin-lighthouse#78]
When running the following command:

_docker run --rm -v "$(pwd):/sitespeed.io" sitespeedio/sitespeed.io:16.10.0-plus1 "https://www.zoopla.co.uk/for-sale/property/london/" --browsertime.iterations 1 --plugins.remove /gpsi_

I get the following error to the terminal:

```
ERROR: Lighthouse could not test https://www.zoopla.co.uk/to-rent/property/london/ please create an upstream issue: https://github.com/GoogleChrome/lighthouse/issues/new?template=Bug_report.md LHError: PROTOCOL_TIMEOUT
    at Timeout._onTimeout (/lighthouse/node_modules/lighthouse/lighthouse-core/gather/driver.js:376:21)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
[2021-03-17 13:30:15] ERROR: TypeError: Cannot read property 'lhr' of undefined
    at Object.processMessage (/lighthouse/index.js:206:28)
```

And in the sitespeed.io report (attached) I get the following error:

`Lighthouse got the following errors: {"name":"LHError","code":"PROTOCOL_TIMEOUT","friendlyMessage":"Waiting for DevTools protocol response has exceeded the allotted time. (Method: Emulation.setScriptExecutionDisabled)","lhrRuntimeError":true,"protocolMethod":"Emulation.setScriptExecutionDisabled"} (lighthouse)`

If I run this locally with Chrome, Lighthouse runs with no issues.

[2021-03-17-13-33-26.zip](https://github.com/sitespeedio/plugin-lighthouse/files/6156769/2021-03-17-13-33-26.zip)

**Comment by shaqb** [comment]
So I did some testing with various versions and using the 6.3 plugin as part of sitespeed.io version 15 works with no issues, but when I upgrade to sitespeed.io version 16.0.0 and lighthouse plugin 7.0.0, that's when I get the error above.

**Comment by soulgalore** [comment]
I think this is an issue with Lighthouse, we had a similar report some time ago but I think that was solved in Lighthouse 7.2, can you try upgrading to 16.10.0 (that contains that Lighthouse version).

**Comment by shaqb** [comment]
Hi @soulgalore it was actually 16.10.0 where I had the original issue, so I started working backwards to 15.

**Comment by soulgalore** [comment]
Ah I see, sorry I missed it. The error comes from Lighthouse, either there's a missmatch with the browser version downloaded by puppeteer and Lighthouse or a Lighthouse bug, that's my guess.

**Comment by shaqb** [comment]
One for Lighthouse then @soulgalore? I can raise it there

**Comment by soulgalore** [comment]
Yes for Lighthouse.
