### ISSUE TITLE
Lighthouse returned error: FAILED_DOCUMENT_REQUEST

### ISSUE THREAD

**Issue by JeanArhancet** [sitespeedio/plugin-lighthouse#94]
Hi,

I currently have an issue with sitespeed 21.3.0-plus1 :

ERROR: [sitespeedio.queuehandler] Error: Lighthouse returned error: FAILED_DOCUMENT_REQUEST. Lighthouse was unable to reliably load the page you requested. Make sure you are testing the correct URL and that the server is properly responding to all requests. (Details: net::ERR_CONNECTION_FAILED)

Any chance, this will be fixed in the future?

Cheers!

**Comment by soulgalore** [comment]
Hi @JeanArhancet that error comes directly from Lighthouse, seems to be a bunch of issues like that : https://github.com/GoogleChrome/lighthouse/search?q=FAILED_DOCUMENT_REQUEST&type=issues

Checkout. https://github.com/GoogleChrome/lighthouse/issues/2784 and maybe there's a fix there, else create an issue at Lighthouse.

Best
Peter
